config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.save
    redirect_to flats_path
  end

  def show
    @flat = Flat.find(params[:id])
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :adress, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-12">
      <h1>All our Flats</h1>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <p>All <%= @flats.length  %> flats</p>
    </div>
  </div>
  <div class="row">
    <% @flats.each do |flat| %>
    <div class="col-4">
      <div class="flat-card">
        <div class="flat-card-content">
          <div class="flat-card-title">
            <h4><%= flat.name %></h4>
          </div>
          <p><%= flat.adress %></p>
          <div class="flex">
            <div class="flex">
              <i class="fa-solid fa-user-group"></i>
              <span><%= flat.number_of_guests %></span>
            </div>
            <div class="flex">
              <i class="fa-solid fa-euro-sign"></i>
              <span><%= flat.price_per_night %></span>
            </div>
          </div>
        </div>
        <div class="flat-card-actions">
          <%= link_to "More Infos", flat_path(flat.id), class:"btn btn-primary" %>
          <a class="btn btn-warning" href="">Edit</a>
          <a class="btn btn-danger" href="">Delete</a>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<h1>New flat</h1>
<%= simple_form_for @flat do |f| %>
  <%= f.input :name %>
  <%= f.input :adress %>
  <%= f.input :description %>
  <%= f.input :number_of_guests %>
  <%= f.input :price_per_night %>
  <%= f.submit %>
<% end %>

app/views/flats/show.html.erb
<h1><%= @flat.name %></h1>
<h2><%= @flat.adress %></h2>
<p><%= @flat.description %></p>
<i class="fa-solid fa-user-group"></i>
<span><%= @flat.number_of_guests %></span>
<br>
<i class="fa-solid fa-euro-sign"></i>
<span><%= @flat.price_per_night %></span>
<br>
<%= link_to "Back to all Flats", flats_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <ul class="nav">
  <li class="nav-item">
    <%= link_to "All Flats", flats_path, class:"nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "Add Flat", new_flat_path, class:"nav-link" %>
  </li>
</ul>
    <%= yield %>
  </body>
</html>